parameters:
#    atonbox_contato.example.class: Atonbox\ContatoBundle\Example

services:
#    atonbox_contato.example:
#        class: %atonbox_contato.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
