parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: projeto_sf2
    database_user: projeto_sf2
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 9d1bdffa6138a66f08f057030da276e22f50d7a4
    database_path: null
