parameters:
#    atonbox_default.example.class: Atonbox\DefaultBundle\Example

services:
#    atonbox_default.example:
#        class: %atonbox_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
